[project]
site_name = "The Firebird library for Python"
site_author = "Pavel Císař"
site_url = "https://firebird-lib.rtfd.io/"
copyright = "2020-2026, The Firebird Project"
nav = [
    { "Home" = "index.md" },
    { "Usage Guide" = [
        { "Introduction" = "usage-guide/introduction.md" },
        { "Working with database schema" = "usage-guide/schema.md" },
        { "Working with monitoring tables" = "usage-guide/monitoring.md" },
        { "Processing gstat output" = "usage-guide/gstat.md" },
        { "Processing Firebird server log" = "usage-guide/firebird-log.md" },
        { "Processing trace sessions" = "usage-guide/trace.md" },
    ] },
    { "Reference" = [
        { "Monitoring" = "ref-monitor.md" },
        { "Schema" = "ref-schema.md" },
        { "Trace" = "ref-trace.md" },
        { "gstat" = "ref-gstat.md" },
        { "Server Log" = "ref-log.md" },
        { "Message Catalog" = "ref-logmsgs.md" },
    ] },
    { "Changelog" = "changelog.md" },
    { "License" = "license.md" },
]

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[project.theme]
favicon = "assets/fb-favicon.png"
features = [
    "navigation.instant",
    "navigation.tracking",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.sections",
    "navigation.expand",
    "navigation.path",
    "navigation.top",
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["../src", "src"]
inventories = [
    "https://docs.python.org/3/objects.inv",
]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_attribute_values = false
show_root_heading = true
show_signature_annotations = true
show_source = true
backlinks = "tree"
find_stubs_package = true

[project.plugins.llmstxt]
enabled = true
markdown_description = "For library version 2.0.1"
sections = {
    "Usage Guide" = [
        "usage-guide/introduction.md",
        "usage-guide/schema.md",
        "usage-guide/monitoring.md",
        "usage-guide/gstat.md",
        "usage-guide/firebird-log.md",
        "usage-guide/trace.md",
    ],
    "Reference" = [
        "ref-schema.md",
        "ref-monitor.md",
        "ref-trace.md",
        "ref-gstat.md",
        "ref-log.md",
        "ref-logmsgs.md"
        ],
}
